source 'https://rubygems.org'

gem 'rails', '4.1.1'

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end

gem 'protected_attributes'
gem 'json'
gem 'active_model_serializers'


